define([], function() {
  return {
    "PropertyPaneDescription": "تكوين الويب بارت",
    "BasicGroupName": "الإعدادات الأساسية",
    "GeneralGroupName": "الإعدادات العامة",
    "DescriptionFieldLabel": "حقل الوصف",
    "ConfigureHeroTitle": "تكوين Hero",
    "ConfigureHeroDescription": "حدد قائمة موجودة أو أنشئ قائمة جديدة لاستخدامها كمصدر محتوى للهوية المميزة.",
    "ExistingListLabel": "قائمة محتوى Hero الحالية",
    "SelectListPlaceholder": "اختر قائمة",
    "UseSelectedListButton": "استخدام القائمة المحددة",
    "CreateHeroListButton": "إنشاء قائمة Hero تلقائياً",
    "CreatingListButton": "جاري الإنشاء...",
    "LoadingMessage": "جاري تحميل المحتوى...",
    "EmptyStateMessage": "لا توجد عناصر نشطة حالياً في قائمة Hero.",
    "ErrorLoadingListsMessage": "تعذر تحميل القوائم المتاحة.",
    "ErrorLoadingItemsMessage": "تعذر تحميل عناصر Hero.",
    "MissingFieldsMessage": "القائمة المختارة لا تحتوي على الحقول المطلوبة:",
    "ListConfiguredMessage": "تم تكوين القائمة بنجاح.",
    "ListCreatedMessage": "تم إنشاء قائمة Hero بنجاح.",
    "CreateListErrorMessage": "تعذرت عملية إنشاء قائمة Hero.",
    "ListSelectionErrorMessage": "يرجى اختيار قائمة صالحة.",
    "PreviousSlideLabel": "الشريحة السابقة",
    "NextSlideLabel": "الشريحة التالية",
    "PaginationLabel": "الشريحة",
    "HeroLayoutLabel": "تخطيط Hero",
    "LayoutFullWidth": "عرض كامل",
    "LayoutFeature": "ميزة",
    "LayoutCarousel": "عرض شرائح",
    "MaxItemsLabel": "الحد الأقصى للعناصر",
    "MaxItemsDescription": "الحد الأقصى لعدد عناصر Hero المراد عرضها.",
    "AutoRotateLabel": "تدوير تلقائي",
    "RotationIntervalLabel": "الفاصل الزمني للتدوير",
    "RotationIntervalDescription": "الفاصل الزمني بين الشرائح بالثواني.",
    "ShowNavigationLabel": "إظهار عناصر التنقل",
    "ShowPaginationLabel": "إظهار مؤشرات الصفحات",
    "HeroHeightLabel": "ارتفاع Hero",
    "HeroHeightDescription": "ارتفاع المكون بالبكسل.",
    "TextAlignLabel": "محاذاة النص",
    "TextAlignLeft": "يسار",
    "TextAlignCenter": "وسط",
    "TextAlignRight": "يمين",
    "OverlayStrengthLabel": "قوة التراكب",
    "OverlayStrengthDescription": "قيمة التراكب فوق الصورة من 0 إلى 100.",
    "OpenLinksInNewWindowLabel": "فتح الروابط في نافذة جديدة",
    "FallbackImageUrlLabel": "عنوان الصورة الاحتياطية",
    "FallbackImageDescription": "عنوان URL لصورة احتياطية عند فقدان الصورة الرئيسية."
  };
});
