define([], function() {
  return {
    "PropertyPaneDescription": "Configure this Hero web part.",
    "BasicGroupName": "Basic settings",
    "GeneralGroupName": "General settings",
    "DescriptionFieldLabel": "Description field",
    "ConfigureHeroTitle": "Configure Hero",
    "ConfigureHeroDescription": "Choose an existing list or create a new one to serve as the Hero content source.",
    "ExistingListLabel": "Existing Hero List",
    "SelectListPlaceholder": "Select a list",
    "UseSelectedListButton": "Use Selected List",
    "CreateHeroListButton": "Create Hero List Automatically",
    "CreatingListButton": "Creating...",
    "LoadingMessage": "Loading Hero content...",
    "EmptyStateMessage": "No active Hero items are available in the configured list.",
    "ErrorLoadingListsMessage": "Unable to load available lists.",
    "ErrorLoadingItemsMessage": "Unable to load Hero items.",
    "MissingFieldsMessage": "The selected list is missing required fields:",
    "ListConfiguredMessage": "Hero list configured successfully.",
    "ListCreatedMessage": "Hero list created successfully.",
    "CreateListErrorMessage": "Unable to create the Hero list.",
    "ListSelectionErrorMessage": "Please select a valid list.",
    "PreviousSlideLabel": "Previous slide",
    "NextSlideLabel": "Next slide",
    "PaginationLabel": "Slide",
    "HeroLayoutLabel": "Hero layout",
    "LayoutFullWidth": "Full-width",
    "LayoutFeature": "Feature",
    "LayoutCarousel": "Carousel",
    "MaxItemsLabel": "Maximum items",
    "MaxItemsDescription": "Maximum number of Hero items to display.",
    "AutoRotateLabel": "Auto rotate",
    "RotationIntervalLabel": "Rotation interval",
    "RotationIntervalDescription": "Time between slides in seconds.",
    "ShowNavigationLabel": "Show navigation controls",
    "ShowPaginationLabel": "Show pagination indicators",
    "HeroHeightLabel": "Hero height",
    "HeroHeightDescription": "Height of the Hero component in pixels.",
    "TextAlignLabel": "Text alignment",
    "TextAlignLeft": "Left",
    "TextAlignCenter": "Center",
    "TextAlignRight": "Right",
    "OverlayStrengthLabel": "Overlay strength",
    "OverlayStrengthDescription": "Overlay intensity from 0 to 100.",
    "OpenLinksInNewWindowLabel": "Open links in new window",
    "FallbackImageUrlLabel": "Fallback image URL",
    "FallbackImageDescription": "Image URL used when a Hero item does not have an image."
  }
});